version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    image: stock_data_visulization_image_flask
    container_name: container_flask_stock_data_visual
    ports:
      - "5010:5010"
    volumes:
      - .:/Project3a
    environment:
      FLASK_DEBUG: "1"